feature/visualization
AtomScott/SoccerTrack pull request #29
Opened 2022-09-16 06:06 UTC by IkumaUchida

- フレーム単位における可視化機能の追加。
- 主なファイルの変更箇所は以下の通り
    - [`file.py`](https://github.com/AtomScott/SoccerTrack/compare/feature/major_refactor...feature/visualization?expand=1#diff-29387e74123a0c408dd23d889885bf39d3e755175d2fd6090a3ed0eea379e754)
    - [`bboxdataframe.py`](https://github.com/AtomScott/SoccerTrack/compare/feature/major_refactor...feature/visualization?expand=1#diff-29387e74123a0c408dd23d889885bf39d3e755175d2fd6090a3ed0eea379e754)

- ImageFont.truetypeにおけるOSErrorへの対応
   - 原因：ローカルのフォントライブラリのパスを引っ張ってくるようになってた為。
       - ユーザの環境によって使用可能なフォントが異なるので、フォント指定方法は変更したい。
   - 対応：[`bboxdataframe.py`](https://github.com/AtomScott/SoccerTrack/compare/feature/major_refactor...feature/visualization?expand=1#diff-29387e74123a0c408dd23d889885bf39d3e755175d2fd6090a3ed0eea379e754)のadd関数においてopencvが用意しているフォントを使用するように指定。（_cv2.FONT{XX}）

2022-09-16 08:45 UTC, IkumaUchida commented
### 機能追加

- 動画に対応した可視化機能の追加。
- 動画を出力するまでの動作を確認
### cheklist

- [ ] 1フレームに対してBBoxを描画
- [ ] 動画に対してBBoxを描画 <- in progress
- [ ] prospectorを通す


主なファイルの変更箇所は以下の通り
    - [`file.py`](https://github.com/AtomScott/SoccerTrack/compare/feature/major_refactor...feature/visualization?expand=1#diff-29387e74123a0c408dd23d889885bf39d3e755175d2fd6090a3ed0eea379e754)
    - [`bboxdataframe.py`](https://github.com/AtomScott/SoccerTrack/compare/feature/major_refactor...feature/visualization?expand=1#diff-29387e74123a0c408dd23d889885bf39d3e755175d2fd6090a3ed0eea379e754)
   - [`bboxdataframe.py`](https://github.com/AtomScott/SoccerTrack/compare/feature/major_refactor...feature/visualization?expand=1#diff-29387e74123a0c408dd23d889885bf39d3e755175d2fd6090a3ed0eea379e754)

2022-09-16 13:22 UTC, AtomScott requested changes
一旦、ここのコメントを直して＆prospector通るようにしてもらえると！

2022-09-16 13:22 UTC, AtomScott commented on soccertrack/utils/DataFrame/bboxdataframe.py
> +        for bbox in bbox_2dim_list:
ここで行われる処理は返り値の`bbox_2dim_list`に含まれなさそう（？）

2022-09-16 13:22 UTC, AtomScott commented on soccertrack/utils/DataFrame/bboxdataframe.py
>              bbox_2dim_list: 2-dim list
一つのbboxの要素を含めた方が親切だと思うので追加してください。
（left, top, width, heightなのか、さらにconf, class_id...が追加されるのか分かりにくい）

2022-09-16 13:22 UTC, AtomScott commented on soccertrack/utils/DataFrame/bboxdataframe.py
>          bbox_2dim_list = [x for x in bbox_2dim_list if not any(pd.isnull(x))]
上記の２重for-loopに含めた方が、2回ループせずに済むと思いました。

2022-09-16 13:22 UTC, AtomScott commented on soccertrack/utils/DataFrame/bboxdataframe.py
> +        ####### How to use（任意のタイミングで削除して頂いて構いません）######
消して大丈夫です。

2022-09-16 13:22 UTC, AtomScott commented on soccertrack/utils/DataFrame/bboxdataframe.py
> +        unique_team_ids = self.columns.get_level_values('TeamID').unique()
この辺り、pandasの関数を使ったり、既に定義したto_list()を活用したりすることでもっとよくできる気がします。

2022-09-16 13:22 UTC, AtomScott commented on soccertrack/utils/DataFrame/bboxdataframe.py
> +        bbox_cols = ['bb_left', 'bb_top', 'bb_width', 'bb_height', 'conf','class_id' ,'obj_id']
`obj_id`ってなんだっけ

2022-09-16 13:22 UTC, AtomScott commented on soccertrack/utils/DataFrame/bboxdataframe.py
> +    # print(colors)
不要なprintは消すか、loggerで出すようにしてください。

2022-09-16 13:22 UTC, AtomScott commented on soccertrack/utils/DataFrame/bboxdataframe.py
> +        fontface = _cv2.FONT_HERSHEY_TRIPLEX  # フォントの種類
日本語コメントも消しちゃってー

2022-09-16 13:22 UTC, AtomScott commented on soccertrack/utils/vis.py
> +from __future__ import annotations
このファイル不要なので消してちゃって大丈夫です。

2022-09-16 13:22 UTC, AtomScott commented on soccertrack/utils/DataFrame/bboxdataframe.py
> +import cv2 as _cv2
cv2, md5としてインポートしてOKです。

2022-09-16 16:31 UTC, IkumaUchida commented on soccertrack/utils/DataFrame/bboxdataframe.py
> +        for bbox in bbox_2dim_list:
リストの値の更新だから、bbox_2dim_listに反映されてると思ってるけど違うかな
https://stackoverflow.com/questions/25410507/how-to-update-or-overwrite-a-python-list

2022-09-16 16:46 UTC, IkumaUchida commented on soccertrack/utils/DataFrame/bboxdataframe.py
> +        unique_team_ids = self.columns.get_level_values('TeamID').unique()
prospector通した後の課題にする。

2022-09-17 00:15 UTC, AtomScott approved these changes

2022-09-17 00:16 UTC, merged