Pull Request: Fix of Mot evaluation
AtomScott/SoccerTrack pull request #43
Opened 2023-01-05 23:48 UTC by IkumaUchida

2023-01-05 23:52 UTC, AtomScott requested changes
簡単な修正点として

- notebookはnotebooks下に置いてもらいたい→notebooks/02とかでいいかな
- 不要なimport, コメントアウトされてるコードを消す
- bboxes_track.preprocess_for_mot_eval()にしてるのは良い。ただ、gt_dets, gt_dets_xyxyが両方あるのはちょっと違和感あるので、gt_detsだけ渡して、to_mot_eval_formatの中でsoccertrack.metrics.object_detectionのconvert_to_x1y1x2y2でconvert_to_x1y1x2y2(gt_dets)をしたりするのはどう？
- to_mot_eval_format()のなかでbboxes_gtをlen()だけで使ってるからなんかびみょいｗ　bboxes_gt渡す必要あるならなんのために関数の外でbboxes_gt.preprocess_for_mot_evalしたの？ってなりそうじゃない？

2023-01-07 10:28 UTC, IkumaUchida commented
mota, identity, hotaのテストコードも追加したんだけど、2点相談
https://github.com/AtomScott/SoccerTrack/pull/43/commits/a32e4cb23e5fe166db18b168f410ae1ba64cdaa5

- map_score同様、mota_score(後の二つも)の入力はBBoxDataFrame以外の入力を受け付けるようにした方が良い？
　- BBoxDataFrameだけだと、今後テストケースの入力のアレンジがしづらいかもと思ったり。
- テストケースが以下の二つ以外思いつかないんだけど他に良さそうなケースはありそうですか？
　1.  trackとgtが完全一致（perfect tracking.）
　2. trackが何も追跡していない（zero tracking.) ->これはtest_ap_score_2関数のzero detectionと同値では？

2. もよくわからないからとりあえず 1. を追加してます

2023-01-07 11:03 UTC, AtomScott commented
ありがとうございます。

> map_score同様、mota_score(＋後の二つ)の入力はBBoxDataFrame以外も受け付けるようにした方が良い？
>　- BBoxDataFrameだけだと、テストケースの入力のアレンジがしづらいかもと思ったり。
[X_INDEX = 0  # xmin, Y_INDEX = 1  # ymin, W_INDEX = 2  # width, H_INDEX = 3  # height, CONFIDENCE_INDEX = 4, CLASS_ID_INDEX = 5, IMAGE_NAME_INDEX = 6]的な配列のリストもありだよね。

>テストケースが以下の二つ以外思いつかないんだけど他に良さそうなケースはありそうですか？
> 1. trackとgtが完全一致（perfect tracking.）
> 2. trackが何も追跡していない（zero tracking.) ->これはtest_ap_score_2関数のzero detectionと同値では？
* その中間を実装するのが大変だから良くないっていうのはわかるので、2フレーム分のtrackとgtを用意して、手計算するのはどうですか？
* 2.に関しては出力が同値ではない（少なくとも同じキーを持った辞書ではない）と思うのであるべきじゃないですかね

他に必要な作業として
* `poetry run pytest`が全部通す（feature/major_refactor branchに追いついていないからだと思います）
* `preprocess_for_mot_eval`のドキュメントを更新する
```
    def preprocess_for_mot_eval(self):
        """Preprocess a dataframe for evaluation using the MOT metrics.
        
        Args:
            self (BBoxDataFrame): BBoxDataFrame object.
        Returns:
            pd.DataFrame: Dataframe in MOT format.
        """
```
* テストの高速化をする。今時間かかってるので、bbdf全部じゃなくて2~5フレームで結果を確認できればいいんじゃないですかね

2023-01-08 08:08 UTC, IkumaUchida commented
上記レビューを反映しました。
[reflect docs change and test acceleration](https://github.com/AtomScott/SoccerTrack/pull/43/commits/fc2f8fdbad1e41292dd34dba7c21cecf5b0d04b9)
[Change index for bbox info to a global variable](https://github.com/AtomScott/SoccerTrack/pull/43/commits/ab0e50783a61695aaf99f0687ff05d4ecdff4269)
[Fix metrics so that tests pass](https://github.com/AtomScott/SoccerTrack/pull/43/commits/fe9f5e4be33cb3728ec84fa869eefd52fef044ec)

テストケースは3種類
- trackとgtが完全に一致
- trackが得られない（False Negative）
- trackとgtが半分だけ一致 

`poetry run pytest`が通ることを確認しています。

あと、`preprocess_for_mot_eval`のドキュメント修正も反映しています。

確認をお願いします。

2023-01-09 10:41 UTC, AtomScott requested changes
いくつか修正点のコメントを残したので確認お願いします。

2023-01-09 10:41 UTC, AtomScott commented on soccertrack/metrics/hota.py
> +    hota_final_scores(res)
反映されていないように見えます。そもそも関数に入れなくてもいいんじゃない？

2023-01-09 10:41 UTC, AtomScott commented on soccertrack/metrics/identity.py
> +    id_final_scores(res)
反映されていないように見えます。そもそも関数に入れなくてもいいんじゃない？

2023-01-09 10:41 UTC, AtomScott commented on soccertrack/metrics/mota.py
>      # """
反映されていないように見えます。そもそも関数に入れなくてもいいんじゃない？

2023-01-09 10:41 UTC, AtomScott commented on tests/test_metrics.py
> +group_list= [group for index, group in bbdf.groupby(level=("TeamID", "PlayerID"), axis=1)]
bbdf.groupbyではなくて、iter_playersの方が適切です。変数名も合わせたほうがいいと思います。

2023-01-09 11:24 UTC, merged