fix/label_upload
AtomScott/SoccerTrack pull request #59
Opened 2023-01-30 07:58 UTC by IkumaUchida

2023-02-02 06:35 UTC, AtomScott requested changes
コメントを残したので修正お願いします！

2023-02-02 06:35 UTC, AtomScott commented on soccertrack/dataframe/bboxdataframe.py
> +    def to_labelbox_data(self, data_row, schema_lookup, KEYFRAME_WINDOW):
KEYFRAME_WINDOWは小文字でお願いします。

2023-02-02 06:35 UTC, AtomScott commented on soccertrack/utils/utils.py
> +def get_labelbox_feature_name(team_id: str, player_id: str) -> str:
カラム名があっていれば、f"{team_id}_{player_id}"で通って欲しいところなのでこの関数は不要だと思います。これからteam_idで3が入ってたりしたらエラーを吐いて欲しいので！

2023-02-02 06:35 UTC, AtomScott commented on soccertrack/dataframe/bboxdataframe.py
> +    def to_labelbox_data(self, data_row, schema_lookup, KEYFRAME_WINDOW):
というか、KEYFRAME_WINDOWは常に１でいいと思うので、そうしちゃってください！どの行を使うかはbbdfを通していじれると思います。

2023-02-03 06:12 UTC, IkumaUchida commented on soccertrack/dataframe/bboxdataframe.py
> +    def to_labelbox_data(self, data_row, schema_lookup, KEYFRAME_WINDOW):
1の場合は、KEYFRAME_WINDOWは何もしないから、消しても良いかな？（決して動くように若干の修正は必要だけど）


https://github.com/AtomScott/SoccerTrack/blob/2e4b81c584c4946f18cbdf7bca3d47e27ec170ae/soccertrack/dataframe/bboxdataframe.py#L293
` if idx % keyframe_window == 0:`

などは不要になります！

2023-02-03 06:15 UTC, IkumaUchida commented on soccertrack/utils/utils.py
> +def get_labelbox_feature_name(team_id: str, player_id: str) -> str:
承知です！

2023-02-04 01:26 UTC, IkumaUchida commented on soccertrack/dataframe/bboxdataframe.py
> +                        key_frames_dict["keyframes"].append(
下記の画像のように、BBoxdataFrame内にNaNが含まれるとき（つまり特定の選手のBBoxがない時）、ValueErrorを吐きます
下記はエラーの例
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[26], line 27
     24 #load the bbdf and convert to labelbox format
     25 bbdf_sample = soccertrack.load_df(bbdf_file_path)
---> 27 labelbox_data = bbdf_sample.to_labelbox_data(data_row, schema_lookup)
     29 # # Use MAL since LabelImport has strict API rate limits
     30 # upload_job = MALPredictionImport.create_from_objects(
     31 #     client = client, 
   (...)
     39 # # Review the upload status
     40 # print(f"Done! Video_name: {data_row.external_id}, Errors: {upload_job.errors}")

File ~/dev_repo/SoccerTrack/soccertrack/dataframe/bboxdataframe.py:327, in BBoxDataFrame.to_labelbox_data(self, data_row, schema_lookup)
    318 """Convert a dataframe to the Labelbox format.
    319 
    320 Args:
   (...)
    324 
    325 """
    326 # convert to labelbox segment format
--> 327 segment = self.to_labelbox_segment()
    329 uploads = []
    330 for schema_name, schema_id in schema_lookup.items():

File ~/dev_repo/SoccerTrack/soccertrack/dataframe/bboxdataframe.py:300, in BBoxDataFrame.to_labelbox_segment(self)
    291 missing_bbox = 0
    293 for idx, row in player_bbdf.iterrows():
    294     # Processing when player_bbdf contains no data
    295     # try:
    296         key_frames_dict["keyframes"].append(
    297             {
    298                 "frame": idx + 1,
    299                 "bbox": {
--> 300                     "top": int(row["bb_top"]),
    301                     "left": int(row["bb_left"]),
    302                     "height": int(row["bb_height"]),
    303                     "width": int(row["bb_width"]),
    304                 },
    305             }
    306         )
    307     # except ValueError as e:
    308     #     missing_bbox += 1
    310 if missing_bbox > 0:

ValueError: cannot convert float NaN to integer
```

![スクリーンショット 2023-02-04 10 16 42](https://user-images.githubusercontent.com/48281753/216737594-c5843d17-54e5-498c-88e0-2d7ba87f49bc.png)


[直近のcommit](https://github.com/AtomScott/SoccerTrack/pull/59#:~:text=11%20minutes%20ago-,fix%20bboxdataframe,-9a8a39d)では、例外処理でlogger.warningを出すようにしています。
選手IDごとに、欠損してるBBoxの数を出すようにしています。

![スクリーンショット 2023-02-04 10 22 55](https://user-images.githubusercontent.com/48281753/216737891-7247a716-e03c-4603-9385-3719ba9e49bb.png)

2023-02-04 01:28 UTC, IkumaUchida commented on soccertrack/dataframe/bboxdataframe.py
> +                        key_frames_dict["keyframes"].append(
ただ、これは入力が悪い場合なので、例外処理せずエラーでも良いかも知れません。

2023-02-07 12:09 UTC, AtomScott approved these changes

2023-02-07 12:10 UTC, merged